- hosts: all
  tasks:
    - name: disable resolved
      ansible.builtin.systemd:
        name: systemd-resolved.service
        state: stopped
        enabled: false

    - name: install dnsmasq
      ansible.builtin.package:
        name: dnsmasq
        state: present

    - name: configure dnsmasq
      ansible.builtin.copy:
        src: dnsmasq.conf
        dest: /etc/dnsmasq.d/internal
        owner: root
        group: root
        mode: '0644'
      notify:
        - restart dnsmasq

    - name: start dnsmasq
      ansible.builtin.systemd:
        name: dnsmasq.service
        state: started
        enabled: true

  handlers:
    - name: restart dnsmasq
      ansible.builtin.systemd:
        name: dnsmasq.service
        state: restarted
